def IPAD = '192.168.1.160' 
def PASS = '123'
node {

    stage ('Publish files'){
        
           sh "scp *.sh opstree@${IPAD}:/home/opstree"

    }
    
    stage ('Install software')
    {
        sh "ssh opstree@192.168.1.160 installHaProxy.sh"
    }

}

