#!/bin/bash

#* Create a pipeline job for rollback with below stages


# 1. Checkout code (checkout code acc to git tag passed by above deployment job)
 #2. Package
  #3. Deployment (Deploy above code to remote server)
  #4. Slack Notification (Notification must contains job console URL)deploy.png*


pipeline {
    agent any
    stages {
        
        stage('Git clone'){
            steps {
                git 'git@github.com:Devpokhariya/spring3hibernate.git'
            }
        }
        stage("input") {
            steps {
                script {
                    env.ROLL_SCOPE = input message: 'Rollback Yes/No', ok:'accept', 
                    parameters: [choice(choices: ['yes', 'no'], 
                    description: '', name: 'param')],
                    submitter: 'qa,devops'
               }
                
            }
        }
        stage ('checkout code') {
            when{
                 expression { "${env.ROLL_SCOPE}" == 'yes' }
            }
            steps {
                sh 'git checkout 1.0 -b 1.0'
            }
            
            
        }
        
        
        stage ('pakcage code') {
             when{
                 expression { "${env.ROLL_SCOPE}" == 'yes' }
            }
            steps {
                sh 'mvn package'
            }
            
            
        }
        
         
        stage ('Deploy code') {
             when{
                 expression { "${env.ROLL_SCOPE}" == 'yes' }
            }
            steps {
                deploy adapters: [tomcat8(credentialsId: 'tomcat', path: '', url: 'http://127.0.0.1:9090/')],  contextPath: 'myapp.war', war: '*/*.war'
            }
            
            
        }
        
         stage ('Email & Slack'){
        steps{
            wrap([$class: 'BuildUser'])
          {
         slackSend channel: 'jenkins-notifications', color: 'warning', message: "Jenkins The build number is ${BUILD_NUMBER} the project name is  ${JOB_NAME} The job console Url ${BUILD_URL} The job is triggered by ", teamDomain: 'opstree', tokenCredentialId: 'slack', username: 'Dev at jenkins'  
    emailext attachLog: true, body: '''This is sent from jenkins code pipeline.
 The build number is ${BUILD_NUMBER}
the project name is  ${JOB_NAME}
The job console Url ${BUILD_URL}
The job is triggered by ${BUILD_CAUSE}''', subject: 'PIpeline code build', to: 'devendra.pokhariya@mygurukulam.org'
        
          }
          }
        }
        
        
    }
}